FROM node:18

WORKDIR /app

# Corrige erro de certificado self-signed (caso necessário)
RUN npm config set strict-ssl false

# Copia todos os arquivos do projeto
COPY . .

# Instala as dependências do projeto
RUN npm install

# Expõe a porta padrão do Vite
EXPOSE 5173

# Roda o servidor de desenvolvimento
CMD ["npm", "run", "dev", "--", "--host"]