version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql80
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "9000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - myapp
    command: --default-authentication-plugin=mysql_native_password

  vite-dev:
    image: node:18
    container_name: vite_dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - myapp
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    
  # laravel:
  #   build: ./laravel
  #   ports:
  #     - "9010:80"
  #   volumes:
  #     - ./laravel:/var/www/html
  #   depends_on:
  #     - mysql
  #   networks:
  #     - myapp

volumes:
  mysql_data:

networks:
  myapp:
    name: myapp